defaults: &defaults
  sharding:
    development:
      master_shard: shard1
      shards:
        shard1:
          master: development
          slave:  development_slave
        shard2:
          master: development2
          slave:  development2_slave
    test:
      master_shard: shard1
      shards:
        shard1:
          master: test
          slave1: test
        shard2:
          master: test2
          slave1: test2

development:
  <<: *defaults

test:
  <<: *defaults
